export const categoryTypes = [
    {
        title: "Grocery",
        description: "Everyday food and drink items",
        background: "#06BF9A",
        color: "#E1F7F3",
        label: "Grocery",
        value: "grocery",
    },
    {
        title: "Toiletries",
        description: "Personal-care essentials",
        background: "#4285F4",
        color: "#E8F0FD",
        label: "Toiletries",
        value: "toiletries",
    },
    {
        title: "Household Supplies",
        description: "Cleaning products, detergents, paper goods",
        background: "#D93025",
        color: "#FAE6E5",
        label: "Household Supplies",
        value: "household supplies",
    },
    {
        title: "Clothing",
        description: "Apparel, shoes, bags, jewelry",
        background: "#F29900",
        color: "#FDF3E0",
        label: "Clothing",
        value: "clothing",
    },
    {   
        title: "Beauty & Skincare",
        description: "Cosmetics, creams, serums, masks",
        background: "#7063F2",
        color: "#EEECFD",
        label: "Beauty & Skincare",
        value: "beauty & skincare",
    },
    {   
        title: "Pet Supplies",
        description: "Pet food, treats, litter, grooming products",
        background: "#FF4065",
        color: "#FFE3E8",
        label: "Pet Supplies",
        value: "pet supplies",
    },
    {   
        title: "Stationery",
        description: "Pens, notebooks, printer paper, cartridges",
        background: "#06BF9A",
        color: "#E1F7F3",
        label: "Stationery",
        value: "stationery",
    },
    {   
        title: "Electronics",
        description: "Phones, laptops, headphones, accessories",
        background: "#4285F4",
        color: "#E8F0FD",
        label: "Electronics",
        value: "electronics",
    },
    {   
        title: "Books/Media",
        description: "Books, e-books, DVDs, games",
        background: "#D93025",
        color: "#FAE6E5",
        label: "books",
        value: "books/media",
    },
    {   
        title: "Wish List",
        description: "Items you want sometime",
        background: "#F29900",
        color: "#FDF3E0",
        label: "Wish List",
        value: "wish list",
    }
]
